name: Otoge
options:
  bundleIdPrefix: dev.sena
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    majorVersion: 5.9.0
  ComposableCoreLocation:
    url: https://github.com/senacand/composable-core-location.git
    branch: swift-concurrency
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    majorVersion: 1.9.0
targets:
  OtogeFinder:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Otoge
    dependencies:
      - package: Alamofire
      - package: ComposableCoreLocation
      - package: ComposableArchitecture
    settings:
      base:
        GENERATE_INFOPLIST_FILE: NO
        MARKETING_VERSION: 0.1.0
        CURRENT_PROJECT_VERSION: 0.1.0.4
        PRODUCT_BUNDLE_IDENTIFIER: dev.sena.otoge
        APP_NAME: Otoge Finder
        TARGETED_DEVICE_FAMILY: 1,2
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    preBuildScripts:
      - script: "${PROJECT_DIR}/swiftgen/bin/swiftgen config run"
        name: SwiftGen
        basedOnDependencyAnalysis: NO
