name: Otoge
options:
  bundleIdPrefix: com.senacand
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    majorVersion: 5.9.0
  ComposableCoreLocation:
    url: https://github.com/senacand/composable-core-location.git
    branch: swift-concurrency
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    majorVersion: 1.9.0
targets:
  OtogeFinder:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Otoge
    dependencies:
      - package: Alamofire
      - package: ComposableCoreLocation
      - package: ComposableArchitecture
    settings:
      base:
        GENERATE_INFOPLIST_FILE: NO
        MARKETING_VERSION: 1.0.0
        PRODUCT_BUNDLE_IDENTIFIER: com.senacand.otoge
        APP_NAME: Otoge Finder
